### PR TITLE
Issue #14853 - resolve CombinedResource base resource during ContextHandler.doStart

### LINKED ISSUE #14853: CombinedResource.getRealURI() returns null when multiple members exist, causing 404 for all static resources
**Jetty version(s)**
12.1.8

**Jetty Environment**
ee11

**HTTP version**
HTTP 1.1

**Java version/vendor**
openjdk 25.0.2 2026-01-20 LTS

**OS type/version**
macOS 26.4.1

**Description**

`ContextHandler.doStart()` introduced in #12970 attempts to resolve an aliased base resource to its canonical path. This works correctly for a simple `PathResource`, but silently does nothing when the base resource is a `CombinedResource` with more than one existing member — `CombinedResource.getRealURI()` returns `null` in that case, so `ContextHandler` only logs a warning and leaves the aliased base resource in place.

The result: every static resource request goes through the full alias-checker path. `SymlinkAllowedResourceAliasChecker` finds no explicit symlink in the URL path segments and returns `false`, causing all static resources to be served as 404.

**Root cause**

`CombinedResource.getRealURI()` returns `null` when more than one member exists on disk:

```java
return switch (exists) {
    case 0 -> _resources.get(0).getRealURI();
    case 1 -> uri;
    default -> null;   // ← returns null when multiple members exist
};
```

`ContextHandler.doStart()` then falls into the warning-only branch:

```java
if (baseResource.isAlias()) {
    URI realUri = baseResource.getRealURI();
    if (realUri == null) {
        LOG.warn("... Base Resource should not be an alias ...");
        // _baseResource is not updated
    } else {
        _baseResource = ResourceFactory.of(this).newResource(realUri);
    }
}
```

**How to reproduce?**

On macOS, `Files.createTempDirectory()` returns paths under `/var/folders/...`, but `/var` is a symlink to `/private/var`. A `CombinedResource` built from two such directories triggers the bug:

```java
Path dir1 = Files.createTempDirectory("web");
Path dir2 = Files.createTempDirectory("overrides");
Files.write(dir1.resolve("test.png"), new byte[]{(byte) 0x89, 'P', 'N', 'G'});

ServletContextHandler handler = new ServletContextHandler();
handler.setBaseResource(ResourceFactory.of(handler).newResource(List.of(dir1.toUri(), dir2.toUri())));
// GET /test.png → 404
```

**Workaround**

Resolve base resource paths to their real paths before constructing the `CombinedResource`:

```java
Path dir1 = Files.createTempDirectory("web").toRealPath();
Path dir2 = Files.createTempDirectory("overrides").toRealPath();
Resource baseResource = ResourceFactory.of(handler).newResource(List.of(dir1.toUri(), dir2.toUri()));
```

**Expected behaviour**

`CombinedResource.getRealURI()` should handle the multi-member case — either by resolving each member to its real URI and constructing a new `CombinedResource`, or by `ContextHandler.doStart()` detecting a `CombinedResource` and rebuilding it member-by-member when `getRealURI()` returns `null`.

**Related**
- #12970 — introduced the `ContextHandler` alias-fix that this gap affects
- #11271 — previous `CombinedResource` + alias checker fix

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Closes #14853

Handle `CombinedResource` when trying to resolve the base resource if it is an alias during `ContextHandler.doStart`.

### CODE REVIEW

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java [hunk 1]
```diff
@@ -892,17 +893,34 @@ protected void doStart() throws Exception
...
+                    List<Resource> resources = combinedResource.getResources().stream()
+                        .map(r ->
+                        {
+                            URI realUri = r.getRealURI();
+                            if (realUri != null)
+                                return resourceFactory.newResource(realUri);
+                            return r;
+                        }).toList();
+                    setAttribute("_baseResource", _baseResource);
+                    _baseResource = ResourceFactory.combine(resources);
```
Comment (sbordet) [inline jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: There should be a comment that says that the attribute stores the "old" base resource.

But frankly, why the old value is stored as an attribute? It could have been a field, without polluting the attributes?
I ask because attributes are then accessible by applications, that can modify them, and this seems just a way to restore the "old" value in `doStop()`.

**Review by sbordet — DISMISSED** [review]
LGTM, but while at it, I would not mind fixing "weird" code.

File: jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java (hunk 1 above)
Comment (lachlan-roberts) [reply jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java]: I have added a comment here.

I am not sure the exact reason why an attribute was used for this, it was done in https://github.com/jetty/jetty.project/pull/12970. I am happy to switch it to a field if you prefer.

I assume an attribute was used only because this is an unusual case and discouraged to set your base resource to an alias in the first place. So the field would only be needed by a rare percentage of deployments who use an aliased base resource.

**Review by sbordet — CHANGES_REQUESTED** [review]
I think a field like `originalBaseResource` is better, and self-explicative.

**Review by sbordet — APPROVED** [review]
