### PR TITLE
Issue #14646 - Problem using `Request.getParameters(request)` with `application/x-www-form-urlencoded;charset=iso-8859-1` with HTTP/2, & HTTP/3

### LINKED ISSUE #14646: Regression in Jetty 12.1: Invalid UTF-8 exception for application/x-www-form-urlencoded; charset=iso-8859-1
**Jetty version(s)**
12.1.7 (12.1.x)

**Jetty Environment**
core

**HTTP version**
2

**Java version/vendor** `(use: java -version)`
25 Corretto

**OS type/version**
any

**Description**

Jetty 12.1.7 doesn't correctly handle ISO-8859-1 encoded requests and returns an error response instead of the expected 200 OK with the example below. The same code is working fine in Jetty 12.0.33.

**How to reproduce?**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.kelunik</groupId>
    <artifactId>jetty-bug-charset</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.jetty.http2</groupId>
            <artifactId>jetty-http2-server</artifactId>
            <version>12.1.7</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.17</version>
        </dependency>
    </dependencies>
</project>
```

```java
package com.kelunik;

import org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory;
import org.eclipse.jetty.server.*;
import org.eclipse.jetty.util.Callback;

import java.nio.ByteBuffer;

public class Main {
    static void main() throws Exception {
        Server server = new Server();

        ServerConnector connector = new ServerConnector(server, new HTTP2ServerConnectionFactory());
        server.addConnector(connector);

        server.setHandler(new Handler.Abstract() {
            @Override
            public boolean handle(Request request, Response response, Callback callback) throws Exception {
                Request.getParameters(request);

                response.write(true, ByteBuffer.wrap(new byte[0]), callback);

                return true;
            }
        });

        server.start();
    }
}
```

`curl --http2-prior-knowledge -v http://localhost:52240 -H 'content-type: application/x-www-form-urlencoded; charset=iso-8859-1' --data 'name=%e9'`

See #14614 for a possible fix.

### PR DESCRIPTION
**Pull request by joakime**
+ Tests form parsing behaviors to ensure that they honor the `charset=iso-8859-1`.
+ Changes to `MimeTypes.getMimeTypeFromContentType(HttpField field)` to not drop charset when looking up well known `MimeTypes.CACHE` entries.

Resolves: #14646

### CODE REVIEW

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/FormTest.java [hunk 1]
```diff
@@ -0,0 +1,237 @@
...
+
+        ContextHandler contextHandler = new ContextHandler();
+        contextHandler.setContextPath("/test");
+        contextHandler.setHandler(new EchoFieldsHandler());
+
+        start(transportType, contextHandler);
+
+        BytesRequestContent formContent = new BytesRequestContent(
+            contentType,
+            "name=%e9".getBytes(UTF_8));
```
Comment (kelunik) [inline jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/FormTest.java:200]: This should be ISO 8859-1 encoding instead of UTF-8, no? Actually doesn't matter, because it's US ASCII range.

File: jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/FormTest.java [hunk 2]
```diff
@@ -227,4 +227,35 @@ protected void service(HttpServletRequest request, HttpServletResponse response)
...
+            {
+                assertEquals(contentType, request.getContentType());
+                Map<String, String[]> params = request.getParameterMap();
+                assertEquals(1, params.size());
+                assertEquals(paramValue, params.get(paramName)[0]);
+            }
+        });
+
+        Fields formParams = new Fields();
+        formParams.add(paramName, paramValue);
```
Comment (kelunik) [inline jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/FormTest.java]: Seems like this test tests with the percent encoded value as literal (so in fact US ASCII range) instead of é. Is that intended?

File: jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/FormTest.java (hunk 1 above)
Comment (joakime) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/FormTest.java:200]: Correct, this is the raw HTTP client form.  Which would be in UTF_8.  The ISO-8859-1 character is already pct-encoded here.

Comment (joakime) [reply jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/FormTest.java:200]: See the assertion below for the `field.name=é\n` output.
This shows that the EchoFieldsHandler got the properly encoded (by ISO-8859-1) character.

File: jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/FormTest.java (hunk 2 above)
Comment (joakime) [reply jetty-ee11/jetty-ee11-servlet/src/test/java/org/eclipse/jetty/ee11/servlet/FormTest.java]: I simplified this testcase a deal to make it more obvious what is going on.

**Review by sbordet — APPROVED** [review]
